//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accident.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int IncidentId { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public string DayNight { get; set; }
        public string DayOfWeek { get; set; }
        public Nullable<int> DeadCount { get; set; }
        public Nullable<int> SeriouslyCount { get; set; }
        public Nullable<int> SlightlyCount { get; set; }
        public Nullable<int> InjuryCount { get; set; }
        public int AccidentFiledId { get; set; }
        public int AccidentTypeId { get; set; }
        public int ViolationId { get; set; }
        public int RoadFormId { get; set; }
        public int AttackerId { get; set; }
        public int VictimId { get; set; }
    
        public virtual AccidentFiled AccidentFiled { get; set; }
        public virtual AccidentType AccidentType { get; set; }
        public virtual AttackerType AttackerType { get; set; }
        public virtual Location Location { get; set; }
        public virtual RoadForm RoadForm { get; set; }
        public virtual VictimType VictimType { get; set; }
        public virtual Violation Violation { get; set; }
    }
}
